add_definitions(-W -Wall -Wno-unused-parameter -fno-strict-aliasing -Wno-unused-function -Wno-deprecated-register)
if(NOT ${CMAKE_BUILD_TYPE} STREQUAL Debug)
    add_definitions("-Ofast")
    add_definitions(-g -rdynamic)
    add_definitions(-march=native -ffast-math)
    add_definitions(-msse -msse2 -msse3 -mfpmath=sse)
    message("[MuseSMC]: Compilining with optimization!")
endif()
